services:
  api:
    build: .
    ports:
      - '${PORT:-3000}:3000'
    environment:
      NODE_ENV: production
      PORT: 3000
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
  
  pgadmin:
      image: dpage/pgadmin4:latest
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
        PGADMIN_CONFIG_SERVER_MODE: 'False'
      ports:
        - "5050:80"
      volumes:
        - pgadmin_data:/var/lib/pgadmin
      depends_on:
        - db
volumes:
  postgres_data:
  pgadmin_data:
